import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        claude: {
          primary: "#cc785c",
          "primary-active": "#a9583e",
          "primary-disabled": "#e6dfd8",
          ink: "#141413",
          body: "#3d3d3a",
          "body-strong": "#252523",
          muted: "#6c6a64",
          "muted-soft": "#8e8b82",
          hairline: "#e6dfd8",
          "hairline-soft": "#ebe6df",
          canvas: "#faf9f5",
          "surface-soft": "#f5f0e8",
          "surface-card": "#efe9de",
          "surface-cream-strong": "#e8e0d2",
          "surface-dark": "#181715",
          "surface-dark-elevated": "#252320",
          "surface-dark-soft": "#1f1e1b",
          "on-primary": "#ffffff",
          "on-dark": "#faf9f5",
          "on-dark-soft": "#a09d96",
          "accent-teal": "#5db8a6",
          "accent-amber": "#e8a55a",
          success: "#5db872",
          warning: "#d4a017",
          error: "#c64545",
        },
      },
      fontFamily: {
        display: ["Copernicus", "Tiempos Headline", "Cormorant Garamond", "serif"],
        heading: ["StyreneB", "Inter", "sans-serif"],
        body: ["StyreneB", "Inter", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        pill: "9999px",
        full: "9999px",
      },
      fontSize: {
        "display-xl": ["64px", { lineHeight: "1.05", letterSpacing: "-1.5px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-1px", fontWeight: "400" }],
        "display-md": ["36px", { lineHeight: "1.15", letterSpacing: "-0.5px", fontWeight: "400" }],
        "display-sm": ["28px", { lineHeight: "1.2", letterSpacing: "-0.3px", fontWeight: "400" }],
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        section: "96px",
      },
    },
  },
  plugins: [],
};
export default config;
